/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getI64Decoder,
  getI64Encoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from '@solana/kit';
import {
  getBurnRateConfigDecoder,
  getBurnRateConfigEncoder,
  getBurnTierDecoder,
  getBurnTierEncoder,
  type BurnRateConfig,
  type BurnRateConfigArgs,
  type BurnTier,
  type BurnTierArgs,
} from '../types';

export const PLATFORM_CONFIG_DISCRIMINATOR = new Uint8Array([
  160, 78, 128, 0, 248, 83, 230, 160,
]);

export function getPlatformConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLATFORM_CONFIG_DISCRIMINATOR
  );
}

export type PlatformConfig = {
  discriminator: ReadonlyUint8Array;
  bump: number;
  admin: Address;
  creator: Address;
  quoteMint: Address;
  poolCreatorFeeBp: number;
  poolTopupFeeBp: number;
  platformFeeBp: number;
  /** Optional global burn authority. If set, every burn instruction on this platform must be signed by this authority. */
  burnAuthority: Option<Address>;
  burnRateConfig: BurnRateConfig;
  burnTiersUpdatedAt: bigint;
  burnTiers: Array<BurnTier>;
};

export type PlatformConfigArgs = {
  bump: number;
  admin: Address;
  creator: Address;
  quoteMint: Address;
  poolCreatorFeeBp: number;
  poolTopupFeeBp: number;
  platformFeeBp: number;
  /** Optional global burn authority. If set, every burn instruction on this platform must be signed by this authority. */
  burnAuthority: OptionOrNullable<Address>;
  burnRateConfig: BurnRateConfigArgs;
  burnTiersUpdatedAt: number | bigint;
  burnTiers: Array<BurnTierArgs>;
};

export function getPlatformConfigEncoder(): Encoder<PlatformConfigArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['bump', getU8Encoder()],
      ['admin', getAddressEncoder()],
      ['creator', getAddressEncoder()],
      ['quoteMint', getAddressEncoder()],
      ['poolCreatorFeeBp', getU16Encoder()],
      ['poolTopupFeeBp', getU16Encoder()],
      ['platformFeeBp', getU16Encoder()],
      ['burnAuthority', getOptionEncoder(getAddressEncoder())],
      ['burnRateConfig', getBurnRateConfigEncoder()],
      ['burnTiersUpdatedAt', getI64Encoder()],
      ['burnTiers', getArrayEncoder(getBurnTierEncoder())],
    ]),
    (value) => ({ ...value, discriminator: PLATFORM_CONFIG_DISCRIMINATOR })
  );
}

export function getPlatformConfigDecoder(): Decoder<PlatformConfig> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['bump', getU8Decoder()],
    ['admin', getAddressDecoder()],
    ['creator', getAddressDecoder()],
    ['quoteMint', getAddressDecoder()],
    ['poolCreatorFeeBp', getU16Decoder()],
    ['poolTopupFeeBp', getU16Decoder()],
    ['platformFeeBp', getU16Decoder()],
    ['burnAuthority', getOptionDecoder(getAddressDecoder())],
    ['burnRateConfig', getBurnRateConfigDecoder()],
    ['burnTiersUpdatedAt', getI64Decoder()],
    ['burnTiers', getArrayDecoder(getBurnTierDecoder())],
  ]);
}

export function getPlatformConfigCodec(): Codec<
  PlatformConfigArgs,
  PlatformConfig
> {
  return combineCodec(getPlatformConfigEncoder(), getPlatformConfigDecoder());
}

export function decodePlatformConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<PlatformConfig, TAddress>;
export function decodePlatformConfig<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<PlatformConfig, TAddress>;
export function decodePlatformConfig<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<PlatformConfig, TAddress> | MaybeAccount<PlatformConfig, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPlatformConfigDecoder()
  );
}

export async function fetchPlatformConfig<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<PlatformConfig, TAddress>> {
  const maybeAccount = await fetchMaybePlatformConfig(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePlatformConfig<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<PlatformConfig, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePlatformConfig(maybeAccount);
}

export async function fetchAllPlatformConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<PlatformConfig>[]> {
  const maybeAccounts = await fetchAllMaybePlatformConfig(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePlatformConfig(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<PlatformConfig>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodePlatformConfig(maybeAccount)
  );
}
