/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from '@solana/kit';
import { CBMM_PROGRAM_ADDRESS } from '../programs';

/** InsufficientVirtualTokenBalance: Insufficient virtual token balance */
export const CBMM_ERROR__INSUFFICIENT_VIRTUAL_TOKEN_BALANCE = 0x1770; // 6000
/** AmountTooSmall: Amount too small */
export const CBMM_ERROR__AMOUNT_TOO_SMALL = 0x1771; // 6001
/** InvalidOwner: Invalid owner */
export const CBMM_ERROR__INVALID_OWNER = 0x1772; // 6002
/** NonzeroBalance: Nonzero balance */
export const CBMM_ERROR__NONZERO_BALANCE = 0x1773; // 6003
/** InvalidFeeBasisPoints: Invalid fee basis points */
export const CBMM_ERROR__INVALID_FEE_BASIS_POINTS = 0x1774; // 6004
/** AmountTooBig: Amount too big */
export const CBMM_ERROR__AMOUNT_TOO_BIG = 0x1775; // 6005
/** SlippageExceeded: Slippage exceeded */
export const CBMM_ERROR__SLIPPAGE_EXCEEDED = 0x1776; // 6006
/** InsufficientBurnAllowance: Insufficient burn allowance */
export const CBMM_ERROR__INSUFFICIENT_BURN_ALLOWANCE = 0x1777; // 6007
/** CannotCloseActiveBurnAllowance: Cannot close active burn allowance */
export const CBMM_ERROR__CANNOT_CLOSE_ACTIVE_BURN_ALLOWANCE = 0x1778; // 6008
/** InvalidBurnAccountPayer: Invalid burn account payer */
export const CBMM_ERROR__INVALID_BURN_ACCOUNT_PAYER = 0x1779; // 6009
/** InvalidVirtualReserve: Invalid virtual reserve */
export const CBMM_ERROR__INVALID_VIRTUAL_RESERVE = 0x177a; // 6010
/** InvalidBuybackFeeBasisPoints: Invalid buyback fee basis points */
export const CBMM_ERROR__INVALID_BUYBACK_FEE_BASIS_POINTS = 0x177b; // 6011
/** Underflow: Underflow */
export const CBMM_ERROR__UNDERFLOW = 0x177c; // 6012
/** InvalidPoolOwner: Invalid pool owner */
export const CBMM_ERROR__INVALID_POOL_OWNER = 0x177d; // 6013
/** InvalidMint: Invalid mint */
export const CBMM_ERROR__INVALID_MINT = 0x177e; // 6014

export type CbmmError =
  | typeof CBMM_ERROR__AMOUNT_TOO_BIG
  | typeof CBMM_ERROR__AMOUNT_TOO_SMALL
  | typeof CBMM_ERROR__CANNOT_CLOSE_ACTIVE_BURN_ALLOWANCE
  | typeof CBMM_ERROR__INSUFFICIENT_BURN_ALLOWANCE
  | typeof CBMM_ERROR__INSUFFICIENT_VIRTUAL_TOKEN_BALANCE
  | typeof CBMM_ERROR__INVALID_BURN_ACCOUNT_PAYER
  | typeof CBMM_ERROR__INVALID_BUYBACK_FEE_BASIS_POINTS
  | typeof CBMM_ERROR__INVALID_FEE_BASIS_POINTS
  | typeof CBMM_ERROR__INVALID_MINT
  | typeof CBMM_ERROR__INVALID_OWNER
  | typeof CBMM_ERROR__INVALID_POOL_OWNER
  | typeof CBMM_ERROR__INVALID_VIRTUAL_RESERVE
  | typeof CBMM_ERROR__NONZERO_BALANCE
  | typeof CBMM_ERROR__SLIPPAGE_EXCEEDED
  | typeof CBMM_ERROR__UNDERFLOW;

let cbmmErrorMessages: Record<CbmmError, string> | undefined;
if (process.env.NODE_ENV !== 'production') {
  cbmmErrorMessages = {
    [CBMM_ERROR__AMOUNT_TOO_BIG]: `Amount too big`,
    [CBMM_ERROR__AMOUNT_TOO_SMALL]: `Amount too small`,
    [CBMM_ERROR__CANNOT_CLOSE_ACTIVE_BURN_ALLOWANCE]: `Cannot close active burn allowance`,
    [CBMM_ERROR__INSUFFICIENT_BURN_ALLOWANCE]: `Insufficient burn allowance`,
    [CBMM_ERROR__INSUFFICIENT_VIRTUAL_TOKEN_BALANCE]: `Insufficient virtual token balance`,
    [CBMM_ERROR__INVALID_BURN_ACCOUNT_PAYER]: `Invalid burn account payer`,
    [CBMM_ERROR__INVALID_BUYBACK_FEE_BASIS_POINTS]: `Invalid buyback fee basis points`,
    [CBMM_ERROR__INVALID_FEE_BASIS_POINTS]: `Invalid fee basis points`,
    [CBMM_ERROR__INVALID_MINT]: `Invalid mint`,
    [CBMM_ERROR__INVALID_OWNER]: `Invalid owner`,
    [CBMM_ERROR__INVALID_POOL_OWNER]: `Invalid pool owner`,
    [CBMM_ERROR__INVALID_VIRTUAL_RESERVE]: `Invalid virtual reserve`,
    [CBMM_ERROR__NONZERO_BALANCE]: `Nonzero balance`,
    [CBMM_ERROR__SLIPPAGE_EXCEEDED]: `Slippage exceeded`,
    [CBMM_ERROR__UNDERFLOW]: `Underflow`,
  };
}

export function getCbmmErrorMessage(code: CbmmError): string {
  if (process.env.NODE_ENV !== 'production') {
    return (cbmmErrorMessages as Record<CbmmError, string>)[code];
  }

  return 'Error message not available in production bundles.';
}

export function isCbmmError<TProgramErrorCode extends CbmmError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    CBMM_PROGRAM_ADDRESS,
    code
  );
}
