[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpmm_poc = "J2rzAsBbYpMVEA3dtuudvzizpbwJXLJgR3yEToKzq1jB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p cpmm-poc -- --nocapture && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
