[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cbmm = "CBMMZBcQnhSAJRpLfD5quaGsDem6WrNDGTr5zSDLCo63"

[programs.devnet]
cbmm = "CBMMZBcQnhSAJRpLfD5quaGsDem6WrNDGTr5zSDLCo63"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./.keypairs/authority.json"

[scripts]
test = "cargo test -p cbmm -- --nocapture && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
