//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLAIM_PLATFORM_FEES_DISCRIMINATOR: [u8; 8] = [159, 129, 37, 35, 170, 99, 163, 16];

/// Accounts.
#[derive(Debug)]
pub struct ClaimPlatformFees {
      
              
          pub admin: solana_pubkey::Pubkey,
          
              
          pub admin_ata: solana_pubkey::Pubkey,
          
              
          pub pool: solana_pubkey::Pubkey,
          
              
          pub pool_ata: solana_pubkey::Pubkey,
          
              
          pub platform_config: solana_pubkey::Pubkey,
          
              
          pub quote_mint: solana_pubkey::Pubkey,
          
              
          pub token_program: solana_pubkey::Pubkey,
          
              
          pub associated_token_program: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
      }

impl ClaimPlatformFees {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.admin,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.admin_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.pool_ata,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.platform_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.quote_mint,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = ClaimPlatformFeesInstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct ClaimPlatformFeesInstructionData {
            discriminator: [u8; 8],
      }

impl ClaimPlatformFeesInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [159, 129, 37, 35, 170, 99, 163, 16],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for ClaimPlatformFeesInstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `ClaimPlatformFees`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin
                ///   1. `[writable]` admin_ata
                ///   2. `[writable]` pool
                ///   3. `[writable]` pool_ata
          ///   4. `[]` platform_config
          ///   5. `[]` quote_mint
                ///   6. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
                ///   7. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
                ///   8. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct ClaimPlatformFeesBuilder {
            admin: Option<solana_pubkey::Pubkey>,
                admin_ata: Option<solana_pubkey::Pubkey>,
                pool: Option<solana_pubkey::Pubkey>,
                pool_ata: Option<solana_pubkey::Pubkey>,
                platform_config: Option<solana_pubkey::Pubkey>,
                quote_mint: Option<solana_pubkey::Pubkey>,
                token_program: Option<solana_pubkey::Pubkey>,
                associated_token_program: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimPlatformFeesBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin = Some(admin);
                    self
    }
            #[inline(always)]
    pub fn admin_ata(&mut self, admin_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin_ata = Some(admin_ata);
                    self
    }
            #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool = Some(pool);
                    self
    }
            #[inline(always)]
    pub fn pool_ata(&mut self, pool_ata: solana_pubkey::Pubkey) -> &mut Self {
                        self.pool_ata = Some(pool_ata);
                    self
    }
            #[inline(always)]
    pub fn platform_config(&mut self, platform_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.platform_config = Some(platform_config);
                    self
    }
            #[inline(always)]
    pub fn quote_mint(&mut self, quote_mint: solana_pubkey::Pubkey) -> &mut Self {
                        self.quote_mint = Some(quote_mint);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
#[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.associated_token_program = Some(associated_token_program);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = ClaimPlatformFees {
                              admin: self.admin.expect("admin is not set"),
                                        admin_ata: self.admin_ata.expect("admin_ata is not set"),
                                        pool: self.pool.expect("pool is not set"),
                                        pool_ata: self.pool_ata.expect("pool_ata is not set"),
                                        platform_config: self.platform_config.expect("platform_config is not set"),
                                        quote_mint: self.quote_mint.expect("quote_mint is not set"),
                                        token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        associated_token_program: self.associated_token_program.unwrap_or(solana_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL")),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `claim_platform_fees` CPI accounts.
  pub struct ClaimPlatformFeesCpiAccounts<'a, 'b> {
          
                    
              pub admin: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub admin_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub pool_ata: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub platform_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub quote_mint: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `claim_platform_fees` CPI instruction.
pub struct ClaimPlatformFeesCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub admin: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub admin_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub pool_ata: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub platform_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub quote_mint: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> ClaimPlatformFeesCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: ClaimPlatformFeesCpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              admin: accounts.admin,
              admin_ata: accounts.admin_ata,
              pool: accounts.pool,
              pool_ata: accounts.pool_ata,
              platform_config: accounts.platform_config,
              quote_mint: accounts.quote_mint,
              token_program: accounts.token_program,
              associated_token_program: accounts.associated_token_program,
              system_program: accounts.system_program,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(9+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.admin.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.admin_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_ata.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.platform_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.quote_mint.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = ClaimPlatformFeesInstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(10 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.admin.clone());
                        account_infos.push(self.admin_ata.clone());
                        account_infos.push(self.pool.clone());
                        account_infos.push(self.pool_ata.clone());
                        account_infos.push(self.platform_config.clone());
                        account_infos.push(self.quote_mint.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.associated_token_program.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `ClaimPlatformFees` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin
                ///   1. `[writable]` admin_ata
                ///   2. `[writable]` pool
                ///   3. `[writable]` pool_ata
          ///   4. `[]` platform_config
          ///   5. `[]` quote_mint
          ///   6. `[]` token_program
          ///   7. `[]` associated_token_program
          ///   8. `[]` system_program
#[derive(Clone, Debug)]
pub struct ClaimPlatformFeesCpiBuilder<'a, 'b> {
  instruction: Box<ClaimPlatformFeesCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimPlatformFeesCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(ClaimPlatformFeesCpiBuilderInstruction {
      __program: program,
              admin: None,
              admin_ata: None,
              pool: None,
              pool_ata: None,
              platform_config: None,
              quote_mint: None,
              token_program: None,
              associated_token_program: None,
              system_program: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin = Some(admin);
                    self
    }
      #[inline(always)]
    pub fn admin_ata(&mut self, admin_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin_ata = Some(admin_ata);
                    self
    }
      #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool = Some(pool);
                    self
    }
      #[inline(always)]
    pub fn pool_ata(&mut self, pool_ata: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool_ata = Some(pool_ata);
                    self
    }
      #[inline(always)]
    pub fn platform_config(&mut self, platform_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.platform_config = Some(platform_config);
                    self
    }
      #[inline(always)]
    pub fn quote_mint(&mut self, quote_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.quote_mint = Some(quote_mint);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn associated_token_program(&mut self, associated_token_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.associated_token_program = Some(associated_token_program);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = ClaimPlatformFeesCpi {
        __program: self.instruction.__program,
                  
          admin: self.instruction.admin.expect("admin is not set"),
                  
          admin_ata: self.instruction.admin_ata.expect("admin_ata is not set"),
                  
          pool: self.instruction.pool.expect("pool is not set"),
                  
          pool_ata: self.instruction.pool_ata.expect("pool_ata is not set"),
                  
          platform_config: self.instruction.platform_config.expect("platform_config is not set"),
                  
          quote_mint: self.instruction.quote_mint.expect("quote_mint is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          associated_token_program: self.instruction.associated_token_program.expect("associated_token_program is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct ClaimPlatformFeesCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            admin: Option<&'b solana_account_info::AccountInfo<'a>>,
                admin_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
                platform_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                quote_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

