//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const INITIALIZE_USER_BURN_ALLOWANCE_DISCRIMINATOR: [u8; 8] = [160, 177, 207, 127, 14, 112, 211, 70];

/// Accounts.
#[derive(Debug)]
pub struct InitializeUserBurnAllowance {
      
              
          pub payer: solana_pubkey::Pubkey,
                /// The user for whom the burn allowance is being initialized

    
              
          pub owner: solana_pubkey::Pubkey,
          
              
          pub user_burn_allowance: solana_pubkey::Pubkey,
          
              
          pub platform_config: solana_pubkey::Pubkey,
          
              
          pub system_program: solana_pubkey::Pubkey,
                /// Optional pool account - only needed if requesting a pool creator burn tier

    
              
          pub pool: Option<solana_pubkey::Pubkey>,
      }

impl InitializeUserBurnAllowance {
  pub fn instruction(&self, args: InitializeUserBurnAllowanceInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitializeUserBurnAllowanceInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.owner,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_burn_allowance,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.platform_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                                      if let Some(pool) = self.pool {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                pool,
                false,
              ));
            } else {
              accounts.push(solana_instruction::AccountMeta::new_readonly(
                crate::CBMM_ID,
                false,
              ));
            }
                                accounts.extend_from_slice(remaining_accounts);
    let mut data = InitializeUserBurnAllowanceInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeUserBurnAllowanceInstructionData {
            discriminator: [u8; 8],
            }

impl InitializeUserBurnAllowanceInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [160, 177, 207, 127, 14, 112, 211, 70],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for InitializeUserBurnAllowanceInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct InitializeUserBurnAllowanceInstructionArgs {
                  pub burn_tier_index: u8,
      }

impl InitializeUserBurnAllowanceInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `InitializeUserBurnAllowance`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
          ///   1. `[]` owner
                ///   2. `[writable]` user_burn_allowance
          ///   3. `[]` platform_config
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   5. `[optional]` pool
#[derive(Clone, Debug, Default)]
pub struct InitializeUserBurnAllowanceBuilder {
            payer: Option<solana_pubkey::Pubkey>,
                owner: Option<solana_pubkey::Pubkey>,
                user_burn_allowance: Option<solana_pubkey::Pubkey>,
                platform_config: Option<solana_pubkey::Pubkey>,
                system_program: Option<solana_pubkey::Pubkey>,
                pool: Option<solana_pubkey::Pubkey>,
                        burn_tier_index: Option<u8>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializeUserBurnAllowanceBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            /// The user for whom the burn allowance is being initialized
#[inline(always)]
    pub fn owner(&mut self, owner: solana_pubkey::Pubkey) -> &mut Self {
                        self.owner = Some(owner);
                    self
    }
            #[inline(always)]
    pub fn user_burn_allowance(&mut self, user_burn_allowance: solana_pubkey::Pubkey) -> &mut Self {
                        self.user_burn_allowance = Some(user_burn_allowance);
                    self
    }
            #[inline(always)]
    pub fn platform_config(&mut self, platform_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.platform_config = Some(platform_config);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account]`
/// Optional pool account - only needed if requesting a pool creator burn tier
#[inline(always)]
    pub fn pool(&mut self, pool: Option<solana_pubkey::Pubkey>) -> &mut Self {
                        self.pool = pool;
                    self
    }
                    #[inline(always)]
      pub fn burn_tier_index(&mut self, burn_tier_index: u8) -> &mut Self {
        self.burn_tier_index = Some(burn_tier_index);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = InitializeUserBurnAllowance {
                              payer: self.payer.expect("payer is not set"),
                                        owner: self.owner.expect("owner is not set"),
                                        user_burn_allowance: self.user_burn_allowance.expect("user_burn_allowance is not set"),
                                        platform_config: self.platform_config.expect("platform_config is not set"),
                                        system_program: self.system_program.unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
                                        pool: self.pool,
                      };
          let args = InitializeUserBurnAllowanceInstructionArgs {
                                                              burn_tier_index: self.burn_tier_index.clone().expect("burn_tier_index is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `initialize_user_burn_allowance` CPI accounts.
  pub struct InitializeUserBurnAllowanceCpiAccounts<'a, 'b> {
          
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                        /// The user for whom the burn allowance is being initialized

      
                    
              pub owner: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_burn_allowance: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub platform_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                        /// Optional pool account - only needed if requesting a pool creator burn tier

      
                    
              pub pool: Option<&'b solana_account_info::AccountInfo<'a>>,
            }

/// `initialize_user_burn_allowance` CPI instruction.
pub struct InitializeUserBurnAllowanceCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
                /// The user for whom the burn allowance is being initialized

    
              
          pub owner: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_burn_allowance: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub platform_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
                /// Optional pool account - only needed if requesting a pool creator burn tier

    
              
          pub pool: Option<&'b solana_account_info::AccountInfo<'a>>,
            /// The arguments for the instruction.
    pub __args: InitializeUserBurnAllowanceInstructionArgs,
  }

impl<'a, 'b> InitializeUserBurnAllowanceCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: InitializeUserBurnAllowanceCpiAccounts<'a, 'b>,
              args: InitializeUserBurnAllowanceInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              payer: accounts.payer,
              owner: accounts.owner,
              user_burn_allowance: accounts.user_burn_allowance,
              platform_config: accounts.platform_config,
              system_program: accounts.system_program,
              pool: accounts.pool,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.owner.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_burn_allowance.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.platform_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          if let Some(pool) = self.pool {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              *pool.key,
              false,
            ));
          } else {
            accounts.push(solana_instruction::AccountMeta::new_readonly(
              crate::CBMM_ID,
              false,
            ));
          }
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = InitializeUserBurnAllowanceInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.payer.clone());
                        account_infos.push(self.owner.clone());
                        account_infos.push(self.user_burn_allowance.clone());
                        account_infos.push(self.platform_config.clone());
                        account_infos.push(self.system_program.clone());
                        if let Some(pool) = self.pool {
          account_infos.push(pool.clone());
        }
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitializeUserBurnAllowance` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
          ///   1. `[]` owner
                ///   2. `[writable]` user_burn_allowance
          ///   3. `[]` platform_config
          ///   4. `[]` system_program
                ///   5. `[optional]` pool
#[derive(Clone, Debug)]
pub struct InitializeUserBurnAllowanceCpiBuilder<'a, 'b> {
  instruction: Box<InitializeUserBurnAllowanceCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeUserBurnAllowanceCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitializeUserBurnAllowanceCpiBuilderInstruction {
      __program: program,
              payer: None,
              owner: None,
              user_burn_allowance: None,
              platform_config: None,
              system_program: None,
              pool: None,
                                            burn_tier_index: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      /// The user for whom the burn allowance is being initialized
#[inline(always)]
    pub fn owner(&mut self, owner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.owner = Some(owner);
                    self
    }
      #[inline(always)]
    pub fn user_burn_allowance(&mut self, user_burn_allowance: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_burn_allowance = Some(user_burn_allowance);
                    self
    }
      #[inline(always)]
    pub fn platform_config(&mut self, platform_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.platform_config = Some(platform_config);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      /// `[optional account]`
/// Optional pool account - only needed if requesting a pool creator burn tier
#[inline(always)]
    pub fn pool(&mut self, pool: Option<&'b solana_account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.pool = pool;
                    self
    }
                    #[inline(always)]
      pub fn burn_tier_index(&mut self, burn_tier_index: u8) -> &mut Self {
        self.instruction.burn_tier_index = Some(burn_tier_index);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = InitializeUserBurnAllowanceInstructionArgs {
                                                              burn_tier_index: self.instruction.burn_tier_index.clone().expect("burn_tier_index is not set"),
                                    };
        let instruction = InitializeUserBurnAllowanceCpi {
        __program: self.instruction.__program,
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          owner: self.instruction.owner.expect("owner is not set"),
                  
          user_burn_allowance: self.instruction.user_burn_allowance.expect("user_burn_allowance is not set"),
                  
          platform_config: self.instruction.platform_config.expect("platform_config is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          pool: self.instruction.pool,
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitializeUserBurnAllowanceCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                owner: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_burn_allowance: Option<&'b solana_account_info::AccountInfo<'a>>,
                platform_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                pool: Option<&'b solana_account_info::AccountInfo<'a>>,
                        burn_tier_index: Option<u8>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

