//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use crate::generated::types::BurnTier;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const UPDATE_PLATFORM_CONFIG_DISCRIMINATOR: [u8; 8] = [195, 60, 76, 129, 146, 45, 67, 143];

/// Accounts.
#[derive(Debug)]
pub struct UpdatePlatformConfig {
      
              
          pub admin: solana_pubkey::Pubkey,
          
              
          pub platform_config: solana_pubkey::Pubkey,
      }

impl UpdatePlatformConfig {
  pub fn instruction(&self, args: UpdatePlatformConfigInstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: UpdatePlatformConfigInstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.admin,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.platform_config,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = UpdatePlatformConfigInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdatePlatformConfigInstructionData {
            discriminator: [u8; 8],
                                                      }

impl UpdatePlatformConfigInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [195, 60, 76, 129, 146, 45, 67, 143],
                                                                                                                                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for UpdatePlatformConfigInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct UpdatePlatformConfigInstructionArgs {
                  pub pool_creator_fee_bp: Option<u16>,
                pub pool_topup_fee_bp: Option<u16>,
                pub platform_fee_bp: Option<u16>,
                pub burn_authority: Option<Option<Pubkey>>,
                pub burn_limit_bp_x100: Option<u64>,
                pub burn_min_bp_x100: Option<u64>,
                pub burn_decay_rate_per_sec_bp_x100: Option<u64>,
                pub burn_tiers: Option<Vec<BurnTier>>,
      }

impl UpdatePlatformConfigInstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `UpdatePlatformConfig`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin
                ///   1. `[writable]` platform_config
#[derive(Clone, Debug, Default)]
pub struct UpdatePlatformConfigBuilder {
            admin: Option<solana_pubkey::Pubkey>,
                platform_config: Option<solana_pubkey::Pubkey>,
                        pool_creator_fee_bp: Option<u16>,
                pool_topup_fee_bp: Option<u16>,
                platform_fee_bp: Option<u16>,
                burn_authority: Option<Option<Pubkey>>,
                burn_limit_bp_x100: Option<u64>,
                burn_min_bp_x100: Option<u64>,
                burn_decay_rate_per_sec_bp_x100: Option<u64>,
                burn_tiers: Option<Vec<BurnTier>>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl UpdatePlatformConfigBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn admin(&mut self, admin: solana_pubkey::Pubkey) -> &mut Self {
                        self.admin = Some(admin);
                    self
    }
            #[inline(always)]
    pub fn platform_config(&mut self, platform_config: solana_pubkey::Pubkey) -> &mut Self {
                        self.platform_config = Some(platform_config);
                    self
    }
                    /// `[optional argument]`
#[inline(always)]
      pub fn pool_creator_fee_bp(&mut self, pool_creator_fee_bp: u16) -> &mut Self {
        self.pool_creator_fee_bp = Some(pool_creator_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn pool_topup_fee_bp(&mut self, pool_topup_fee_bp: u16) -> &mut Self {
        self.pool_topup_fee_bp = Some(pool_topup_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn platform_fee_bp(&mut self, platform_fee_bp: u16) -> &mut Self {
        self.platform_fee_bp = Some(platform_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_authority(&mut self, burn_authority: Option<Pubkey>) -> &mut Self {
        self.burn_authority = Some(burn_authority);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_limit_bp_x100(&mut self, burn_limit_bp_x100: u64) -> &mut Self {
        self.burn_limit_bp_x100 = Some(burn_limit_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_min_bp_x100(&mut self, burn_min_bp_x100: u64) -> &mut Self {
        self.burn_min_bp_x100 = Some(burn_min_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_decay_rate_per_sec_bp_x100(&mut self, burn_decay_rate_per_sec_bp_x100: u64) -> &mut Self {
        self.burn_decay_rate_per_sec_bp_x100 = Some(burn_decay_rate_per_sec_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_tiers(&mut self, burn_tiers: Vec<BurnTier>) -> &mut Self {
        self.burn_tiers = Some(burn_tiers);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = UpdatePlatformConfig {
                              admin: self.admin.expect("admin is not set"),
                                        platform_config: self.platform_config.expect("platform_config is not set"),
                      };
          let args = UpdatePlatformConfigInstructionArgs {
                                                              pool_creator_fee_bp: self.pool_creator_fee_bp.clone(),
                                                                  pool_topup_fee_bp: self.pool_topup_fee_bp.clone(),
                                                                  platform_fee_bp: self.platform_fee_bp.clone(),
                                                                  burn_authority: self.burn_authority.clone(),
                                                                  burn_limit_bp_x100: self.burn_limit_bp_x100.clone(),
                                                                  burn_min_bp_x100: self.burn_min_bp_x100.clone(),
                                                                  burn_decay_rate_per_sec_bp_x100: self.burn_decay_rate_per_sec_bp_x100.clone(),
                                                                  burn_tiers: self.burn_tiers.clone(),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `update_platform_config` CPI accounts.
  pub struct UpdatePlatformConfigCpiAccounts<'a, 'b> {
          
                    
              pub admin: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub platform_config: &'b solana_account_info::AccountInfo<'a>,
            }

/// `update_platform_config` CPI instruction.
pub struct UpdatePlatformConfigCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub admin: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub platform_config: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: UpdatePlatformConfigInstructionArgs,
  }

impl<'a, 'b> UpdatePlatformConfigCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: UpdatePlatformConfigCpiAccounts<'a, 'b>,
              args: UpdatePlatformConfigInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              admin: accounts.admin,
              platform_config: accounts.platform_config,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(2+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.admin.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.platform_config.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = UpdatePlatformConfigInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::CBMM_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(3 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.admin.clone());
                        account_infos.push(self.platform_config.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `UpdatePlatformConfig` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` admin
                ///   1. `[writable]` platform_config
#[derive(Clone, Debug)]
pub struct UpdatePlatformConfigCpiBuilder<'a, 'b> {
  instruction: Box<UpdatePlatformConfigCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> UpdatePlatformConfigCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(UpdatePlatformConfigCpiBuilderInstruction {
      __program: program,
              admin: None,
              platform_config: None,
                                            pool_creator_fee_bp: None,
                                pool_topup_fee_bp: None,
                                platform_fee_bp: None,
                                burn_authority: None,
                                burn_limit_bp_x100: None,
                                burn_min_bp_x100: None,
                                burn_decay_rate_per_sec_bp_x100: None,
                                burn_tiers: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.admin = Some(admin);
                    self
    }
      #[inline(always)]
    pub fn platform_config(&mut self, platform_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.platform_config = Some(platform_config);
                    self
    }
                    /// `[optional argument]`
#[inline(always)]
      pub fn pool_creator_fee_bp(&mut self, pool_creator_fee_bp: u16) -> &mut Self {
        self.instruction.pool_creator_fee_bp = Some(pool_creator_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn pool_topup_fee_bp(&mut self, pool_topup_fee_bp: u16) -> &mut Self {
        self.instruction.pool_topup_fee_bp = Some(pool_topup_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn platform_fee_bp(&mut self, platform_fee_bp: u16) -> &mut Self {
        self.instruction.platform_fee_bp = Some(platform_fee_bp);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_authority(&mut self, burn_authority: Option<Pubkey>) -> &mut Self {
        self.instruction.burn_authority = Some(burn_authority);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_limit_bp_x100(&mut self, burn_limit_bp_x100: u64) -> &mut Self {
        self.instruction.burn_limit_bp_x100 = Some(burn_limit_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_min_bp_x100(&mut self, burn_min_bp_x100: u64) -> &mut Self {
        self.instruction.burn_min_bp_x100 = Some(burn_min_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_decay_rate_per_sec_bp_x100(&mut self, burn_decay_rate_per_sec_bp_x100: u64) -> &mut Self {
        self.instruction.burn_decay_rate_per_sec_bp_x100 = Some(burn_decay_rate_per_sec_bp_x100);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn burn_tiers(&mut self, burn_tiers: Vec<BurnTier>) -> &mut Self {
        self.instruction.burn_tiers = Some(burn_tiers);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = UpdatePlatformConfigInstructionArgs {
                                                              pool_creator_fee_bp: self.instruction.pool_creator_fee_bp.clone(),
                                                                  pool_topup_fee_bp: self.instruction.pool_topup_fee_bp.clone(),
                                                                  platform_fee_bp: self.instruction.platform_fee_bp.clone(),
                                                                  burn_authority: self.instruction.burn_authority.clone(),
                                                                  burn_limit_bp_x100: self.instruction.burn_limit_bp_x100.clone(),
                                                                  burn_min_bp_x100: self.instruction.burn_min_bp_x100.clone(),
                                                                  burn_decay_rate_per_sec_bp_x100: self.instruction.burn_decay_rate_per_sec_bp_x100.clone(),
                                                                  burn_tiers: self.instruction.burn_tiers.clone(),
                                    };
        let instruction = UpdatePlatformConfigCpi {
        __program: self.instruction.__program,
                  
          admin: self.instruction.admin.expect("admin is not set"),
                  
          platform_config: self.instruction.platform_config.expect("platform_config is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct UpdatePlatformConfigCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            admin: Option<&'b solana_account_info::AccountInfo<'a>>,
                platform_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                        pool_creator_fee_bp: Option<u16>,
                pool_topup_fee_bp: Option<u16>,
                platform_fee_bp: Option<u16>,
                burn_authority: Option<Option<Pubkey>>,
                burn_limit_bp_x100: Option<u64>,
                burn_min_bp_x100: Option<u64>,
                burn_decay_rate_per_sec_bp_x100: Option<u64>,
                burn_tiers: Option<Vec<BurnTier>>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

