//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BurnRateLimiter {
/// Executed burns ("heat") that decay over time.
pub accumulated_stress_bp_x10k: u64,
/// Pending burns in the queue; does not decay.
pub pending_queue_shares_bp_x10k: u64,
pub last_update_ts: i64,
}


