//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BuyEvent {
pub a_input: u64,
pub b_output: u64,
pub creator_fees: u64,
pub buyback_fees: u64,
pub platform_fees: u64,
pub topup_paid: u64,
pub new_b_reserve: u64,
pub new_a_reserve: u64,
pub new_outstanding_topup: u64,
pub new_creator_fees_balance: u64,
pub new_buyback_fees_balance: u64,
}


