//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::Pubkey;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SellEvent {
pub b_input: u64,
pub a_output: u64,
pub creator_fees: u64,
pub buyback_fees: u64,
pub platform_fees: u64,
pub topup_paid: u64,
pub new_b_reserve: u64,
pub new_a_reserve: u64,
pub new_outstanding_topup: u64,
pub new_creator_fees_balance: u64,
pub new_buyback_fees_balance: u64,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub seller: Pubkey,
#[cfg_attr(feature = "serde", serde(with = "serde_with::As::<serde_with::DisplayFromStr>"))]
pub pool: Pubkey,
}


