/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { CBMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const BURN_VIRTUAL_TOKEN_DISCRIMINATOR = new Uint8Array([
  27, 21, 118, 210, 92, 230, 68, 59,
]);

export function getBurnVirtualTokenDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    BURN_VIRTUAL_TOKEN_DISCRIMINATOR
  );
}

export type BurnVirtualTokenInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountUserBurnAllowance extends string | AccountMeta<string> = string,
  TAccountCentralState extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountUserBurnAllowance extends string
        ? WritableAccount<TAccountUserBurnAllowance>
        : TAccountUserBurnAllowance,
      TAccountCentralState extends string
        ? WritableAccount<TAccountCentralState>
        : TAccountCentralState,
      ...TRemainingAccounts,
    ]
  >;

export type BurnVirtualTokenInstructionData = {
  discriminator: ReadonlyUint8Array;
  poolOwner: boolean;
};

export type BurnVirtualTokenInstructionDataArgs = { poolOwner: boolean };

export function getBurnVirtualTokenInstructionDataEncoder(): FixedSizeEncoder<BurnVirtualTokenInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['poolOwner', getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: BURN_VIRTUAL_TOKEN_DISCRIMINATOR })
  );
}

export function getBurnVirtualTokenInstructionDataDecoder(): FixedSizeDecoder<BurnVirtualTokenInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['poolOwner', getBooleanDecoder()],
  ]);
}

export function getBurnVirtualTokenInstructionDataCodec(): FixedSizeCodec<
  BurnVirtualTokenInstructionDataArgs,
  BurnVirtualTokenInstructionData
> {
  return combineCodec(
    getBurnVirtualTokenInstructionDataEncoder(),
    getBurnVirtualTokenInstructionDataDecoder()
  );
}

export type BurnVirtualTokenAsyncInput<
  TAccountSigner extends string = string,
  TAccountPool extends string = string,
  TAccountUserBurnAllowance extends string = string,
  TAccountCentralState extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  pool: Address<TAccountPool>;
  userBurnAllowance: Address<TAccountUserBurnAllowance>;
  centralState?: Address<TAccountCentralState>;
  poolOwner: BurnVirtualTokenInstructionDataArgs['poolOwner'];
};

export async function getBurnVirtualTokenInstructionAsync<
  TAccountSigner extends string,
  TAccountPool extends string,
  TAccountUserBurnAllowance extends string,
  TAccountCentralState extends string,
  TProgramAddress extends Address = typeof CBMM_PROGRAM_ADDRESS,
>(
  input: BurnVirtualTokenAsyncInput<
    TAccountSigner,
    TAccountPool,
    TAccountUserBurnAllowance,
    TAccountCentralState
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  BurnVirtualTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPool,
    TAccountUserBurnAllowance,
    TAccountCentralState
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CBMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    userBurnAllowance: {
      value: input.userBurnAllowance ?? null,
      isWritable: true,
    },
    centralState: { value: input.centralState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.centralState.value) {
    accounts.centralState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            99, 101, 110, 116, 114, 97, 108, 95, 115, 116, 97, 116, 101,
          ])
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.userBurnAllowance),
      getAccountMeta(accounts.centralState),
    ],
    data: getBurnVirtualTokenInstructionDataEncoder().encode(
      args as BurnVirtualTokenInstructionDataArgs
    ),
    programAddress,
  } as BurnVirtualTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPool,
    TAccountUserBurnAllowance,
    TAccountCentralState
  >);
}

export type BurnVirtualTokenInput<
  TAccountSigner extends string = string,
  TAccountPool extends string = string,
  TAccountUserBurnAllowance extends string = string,
  TAccountCentralState extends string = string,
> = {
  signer: TransactionSigner<TAccountSigner>;
  pool: Address<TAccountPool>;
  userBurnAllowance: Address<TAccountUserBurnAllowance>;
  centralState: Address<TAccountCentralState>;
  poolOwner: BurnVirtualTokenInstructionDataArgs['poolOwner'];
};

export function getBurnVirtualTokenInstruction<
  TAccountSigner extends string,
  TAccountPool extends string,
  TAccountUserBurnAllowance extends string,
  TAccountCentralState extends string,
  TProgramAddress extends Address = typeof CBMM_PROGRAM_ADDRESS,
>(
  input: BurnVirtualTokenInput<
    TAccountSigner,
    TAccountPool,
    TAccountUserBurnAllowance,
    TAccountCentralState
  >,
  config?: { programAddress?: TProgramAddress }
): BurnVirtualTokenInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountPool,
  TAccountUserBurnAllowance,
  TAccountCentralState
> {
  // Program address.
  const programAddress = config?.programAddress ?? CBMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    pool: { value: input.pool ?? null, isWritable: true },
    userBurnAllowance: {
      value: input.userBurnAllowance ?? null,
      isWritable: true,
    },
    centralState: { value: input.centralState ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.signer),
      getAccountMeta(accounts.pool),
      getAccountMeta(accounts.userBurnAllowance),
      getAccountMeta(accounts.centralState),
    ],
    data: getBurnVirtualTokenInstructionDataEncoder().encode(
      args as BurnVirtualTokenInstructionDataArgs
    ),
    programAddress,
  } as BurnVirtualTokenInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPool,
    TAccountUserBurnAllowance,
    TAccountCentralState
  >);
}

export type ParsedBurnVirtualTokenInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    signer: TAccountMetas[0];
    pool: TAccountMetas[1];
    userBurnAllowance: TAccountMetas[2];
    centralState: TAccountMetas[3];
  };
  data: BurnVirtualTokenInstructionData;
};

export function parseBurnVirtualTokenInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedBurnVirtualTokenInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      pool: getNextAccount(),
      userBurnAllowance: getNextAccount(),
      centralState: getNextAccount(),
    },
    data: getBurnVirtualTokenInstructionDataDecoder().decode(instruction.data),
  };
}
