/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from '@solana/kit';
import { CBMM_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const CLOSE_USER_BURN_ALLOWANCE_DISCRIMINATOR = new Uint8Array([
  217, 24, 207, 62, 181, 123, 16, 187,
]);

export function getCloseUserBurnAllowanceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_USER_BURN_ALLOWANCE_DISCRIMINATOR
  );
}

export type CloseUserBurnAllowanceInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountOwner extends string | AccountMeta<string> = string,
  TAccountUserBurnAllowance extends string | AccountMeta<string> = string,
  TAccountPlatformConfig extends string | AccountMeta<string> = string,
  TAccountBurnAllowanceOpenPayer extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountOwner extends string
        ? ReadonlyAccount<TAccountOwner>
        : TAccountOwner,
      TAccountUserBurnAllowance extends string
        ? WritableAccount<TAccountUserBurnAllowance>
        : TAccountUserBurnAllowance,
      TAccountPlatformConfig extends string
        ? ReadonlyAccount<TAccountPlatformConfig>
        : TAccountPlatformConfig,
      TAccountBurnAllowanceOpenPayer extends string
        ? ReadonlyAccount<TAccountBurnAllowanceOpenPayer>
        : TAccountBurnAllowanceOpenPayer,
      ...TRemainingAccounts,
    ]
  >;

export type CloseUserBurnAllowanceInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseUserBurnAllowanceInstructionDataArgs = {};

export function getCloseUserBurnAllowanceInstructionDataEncoder(): FixedSizeEncoder<CloseUserBurnAllowanceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([['discriminator', fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_USER_BURN_ALLOWANCE_DISCRIMINATOR,
    })
  );
}

export function getCloseUserBurnAllowanceInstructionDataDecoder(): FixedSizeDecoder<CloseUserBurnAllowanceInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseUserBurnAllowanceInstructionDataCodec(): FixedSizeCodec<
  CloseUserBurnAllowanceInstructionDataArgs,
  CloseUserBurnAllowanceInstructionData
> {
  return combineCodec(
    getCloseUserBurnAllowanceInstructionDataEncoder(),
    getCloseUserBurnAllowanceInstructionDataDecoder()
  );
}

export type CloseUserBurnAllowanceInput<
  TAccountOwner extends string = string,
  TAccountUserBurnAllowance extends string = string,
  TAccountPlatformConfig extends string = string,
  TAccountBurnAllowanceOpenPayer extends string = string,
> = {
  /** The user whose burn allowance is being closed */
  owner: Address<TAccountOwner>;
  userBurnAllowance: Address<TAccountUserBurnAllowance>;
  platformConfig: Address<TAccountPlatformConfig>;
  burnAllowanceOpenPayer: Address<TAccountBurnAllowanceOpenPayer>;
};

export function getCloseUserBurnAllowanceInstruction<
  TAccountOwner extends string,
  TAccountUserBurnAllowance extends string,
  TAccountPlatformConfig extends string,
  TAccountBurnAllowanceOpenPayer extends string,
  TProgramAddress extends Address = typeof CBMM_PROGRAM_ADDRESS,
>(
  input: CloseUserBurnAllowanceInput<
    TAccountOwner,
    TAccountUserBurnAllowance,
    TAccountPlatformConfig,
    TAccountBurnAllowanceOpenPayer
  >,
  config?: { programAddress?: TProgramAddress }
): CloseUserBurnAllowanceInstruction<
  TProgramAddress,
  TAccountOwner,
  TAccountUserBurnAllowance,
  TAccountPlatformConfig,
  TAccountBurnAllowanceOpenPayer
> {
  // Program address.
  const programAddress = config?.programAddress ?? CBMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    owner: { value: input.owner ?? null, isWritable: false },
    userBurnAllowance: {
      value: input.userBurnAllowance ?? null,
      isWritable: true,
    },
    platformConfig: { value: input.platformConfig ?? null, isWritable: false },
    burnAllowanceOpenPayer: {
      value: input.burnAllowanceOpenPayer ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.owner),
      getAccountMeta(accounts.userBurnAllowance),
      getAccountMeta(accounts.platformConfig),
      getAccountMeta(accounts.burnAllowanceOpenPayer),
    ],
    data: getCloseUserBurnAllowanceInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseUserBurnAllowanceInstruction<
    TProgramAddress,
    TAccountOwner,
    TAccountUserBurnAllowance,
    TAccountPlatformConfig,
    TAccountBurnAllowanceOpenPayer
  >);
}

export type ParsedCloseUserBurnAllowanceInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** The user whose burn allowance is being closed */
    owner: TAccountMetas[0];
    userBurnAllowance: TAccountMetas[1];
    platformConfig: TAccountMetas[2];
    burnAllowanceOpenPayer: TAccountMetas[3];
  };
  data: CloseUserBurnAllowanceInstructionData;
};

export function parseCloseUserBurnAllowanceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseUserBurnAllowanceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      owner: getNextAccount(),
      userBurnAllowance: getNextAccount(),
      platformConfig: getNextAccount(),
      burnAllowanceOpenPayer: getNextAccount(),
    },
    data: getCloseUserBurnAllowanceInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
