/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { CBMM_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';
import {
  getBurnTierDecoder,
  getBurnTierEncoder,
  type BurnTier,
  type BurnTierArgs,
} from '../types';

export const INITIALIZE_PLATFORM_CONFIG_DISCRIMINATOR = new Uint8Array([
  23, 52, 237, 53, 176, 235, 3, 187,
]);

export function getInitializePlatformConfigDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_PLATFORM_CONFIG_DISCRIMINATOR
  );
}

export type InitializePlatformConfigInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountCreator extends string | AccountMeta<string> = string,
  TAccountPlatformConfig extends string | AccountMeta<string> = string,
  TAccountQuoteMint extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountCreator extends string
        ? WritableSignerAccount<TAccountCreator> &
            AccountSignerMeta<TAccountCreator>
        : TAccountCreator,
      TAccountPlatformConfig extends string
        ? WritableAccount<TAccountPlatformConfig>
        : TAccountPlatformConfig,
      TAccountQuoteMint extends string
        ? ReadonlyAccount<TAccountQuoteMint>
        : TAccountQuoteMint,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializePlatformConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  creatorFeeBp: number;
  topupFeeBp: number;
  platformFeeBp: number;
  /** Optional global burn authority required to sign all burns on this platform */
  burnAuthority: Option<Address>;
  burnLimitBpX100: bigint;
  burnMinBurnBpX100: bigint;
  burnDecayRatePerSecBpX100: bigint;
  burnTiers: Array<BurnTier>;
};

export type InitializePlatformConfigInstructionDataArgs = {
  creatorFeeBp: number;
  topupFeeBp: number;
  platformFeeBp: number;
  /** Optional global burn authority required to sign all burns on this platform */
  burnAuthority: OptionOrNullable<Address>;
  burnLimitBpX100: number | bigint;
  burnMinBurnBpX100: number | bigint;
  burnDecayRatePerSecBpX100: number | bigint;
  burnTiers: Array<BurnTierArgs>;
};

export function getInitializePlatformConfigInstructionDataEncoder(): Encoder<InitializePlatformConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['creatorFeeBp', getU16Encoder()],
      ['topupFeeBp', getU16Encoder()],
      ['platformFeeBp', getU16Encoder()],
      ['burnAuthority', getOptionEncoder(getAddressEncoder())],
      ['burnLimitBpX100', getU64Encoder()],
      ['burnMinBurnBpX100', getU64Encoder()],
      ['burnDecayRatePerSecBpX100', getU64Encoder()],
      ['burnTiers', getArrayEncoder(getBurnTierEncoder())],
    ]),
    (value) => ({
      ...value,
      discriminator: INITIALIZE_PLATFORM_CONFIG_DISCRIMINATOR,
    })
  );
}

export function getInitializePlatformConfigInstructionDataDecoder(): Decoder<InitializePlatformConfigInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['creatorFeeBp', getU16Decoder()],
    ['topupFeeBp', getU16Decoder()],
    ['platformFeeBp', getU16Decoder()],
    ['burnAuthority', getOptionDecoder(getAddressDecoder())],
    ['burnLimitBpX100', getU64Decoder()],
    ['burnMinBurnBpX100', getU64Decoder()],
    ['burnDecayRatePerSecBpX100', getU64Decoder()],
    ['burnTiers', getArrayDecoder(getBurnTierDecoder())],
  ]);
}

export function getInitializePlatformConfigInstructionDataCodec(): Codec<
  InitializePlatformConfigInstructionDataArgs,
  InitializePlatformConfigInstructionData
> {
  return combineCodec(
    getInitializePlatformConfigInstructionDataEncoder(),
    getInitializePlatformConfigInstructionDataDecoder()
  );
}

export type InitializePlatformConfigAsyncInput<
  TAccountCreator extends string = string,
  TAccountPlatformConfig extends string = string,
  TAccountQuoteMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  creator: TransactionSigner<TAccountCreator>;
  platformConfig?: Address<TAccountPlatformConfig>;
  quoteMint: Address<TAccountQuoteMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  creatorFeeBp: InitializePlatformConfigInstructionDataArgs['creatorFeeBp'];
  topupFeeBp: InitializePlatformConfigInstructionDataArgs['topupFeeBp'];
  platformFeeBp: InitializePlatformConfigInstructionDataArgs['platformFeeBp'];
  burnAuthority: InitializePlatformConfigInstructionDataArgs['burnAuthority'];
  burnLimitBpX100: InitializePlatformConfigInstructionDataArgs['burnLimitBpX100'];
  burnMinBurnBpX100: InitializePlatformConfigInstructionDataArgs['burnMinBurnBpX100'];
  burnDecayRatePerSecBpX100: InitializePlatformConfigInstructionDataArgs['burnDecayRatePerSecBpX100'];
  burnTiers: InitializePlatformConfigInstructionDataArgs['burnTiers'];
};

export async function getInitializePlatformConfigInstructionAsync<
  TAccountCreator extends string,
  TAccountPlatformConfig extends string,
  TAccountQuoteMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CBMM_PROGRAM_ADDRESS,
>(
  input: InitializePlatformConfigAsyncInput<
    TAccountCreator,
    TAccountPlatformConfig,
    TAccountQuoteMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializePlatformConfigInstruction<
    TProgramAddress,
    TAccountCreator,
    TAccountPlatformConfig,
    TAccountQuoteMint,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CBMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    creator: { value: input.creator ?? null, isWritable: true },
    platformConfig: { value: input.platformConfig ?? null, isWritable: true },
    quoteMint: { value: input.quoteMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.platformConfig.value) {
    accounts.platformConfig.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            112, 108, 97, 116, 102, 111, 114, 109, 95, 99, 111, 110, 102, 105,
            103,
          ])
        ),
        getAddressEncoder().encode(expectAddress(accounts.creator.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.platformConfig),
      getAccountMeta(accounts.quoteMint),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializePlatformConfigInstructionDataEncoder().encode(
      args as InitializePlatformConfigInstructionDataArgs
    ),
    programAddress,
  } as InitializePlatformConfigInstruction<
    TProgramAddress,
    TAccountCreator,
    TAccountPlatformConfig,
    TAccountQuoteMint,
    TAccountSystemProgram
  >);
}

export type InitializePlatformConfigInput<
  TAccountCreator extends string = string,
  TAccountPlatformConfig extends string = string,
  TAccountQuoteMint extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  creator: TransactionSigner<TAccountCreator>;
  platformConfig: Address<TAccountPlatformConfig>;
  quoteMint: Address<TAccountQuoteMint>;
  systemProgram?: Address<TAccountSystemProgram>;
  creatorFeeBp: InitializePlatformConfigInstructionDataArgs['creatorFeeBp'];
  topupFeeBp: InitializePlatformConfigInstructionDataArgs['topupFeeBp'];
  platformFeeBp: InitializePlatformConfigInstructionDataArgs['platformFeeBp'];
  burnAuthority: InitializePlatformConfigInstructionDataArgs['burnAuthority'];
  burnLimitBpX100: InitializePlatformConfigInstructionDataArgs['burnLimitBpX100'];
  burnMinBurnBpX100: InitializePlatformConfigInstructionDataArgs['burnMinBurnBpX100'];
  burnDecayRatePerSecBpX100: InitializePlatformConfigInstructionDataArgs['burnDecayRatePerSecBpX100'];
  burnTiers: InitializePlatformConfigInstructionDataArgs['burnTiers'];
};

export function getInitializePlatformConfigInstruction<
  TAccountCreator extends string,
  TAccountPlatformConfig extends string,
  TAccountQuoteMint extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CBMM_PROGRAM_ADDRESS,
>(
  input: InitializePlatformConfigInput<
    TAccountCreator,
    TAccountPlatformConfig,
    TAccountQuoteMint,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializePlatformConfigInstruction<
  TProgramAddress,
  TAccountCreator,
  TAccountPlatformConfig,
  TAccountQuoteMint,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CBMM_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    creator: { value: input.creator ?? null, isWritable: true },
    platformConfig: { value: input.platformConfig ?? null, isWritable: true },
    quoteMint: { value: input.quoteMint ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.creator),
      getAccountMeta(accounts.platformConfig),
      getAccountMeta(accounts.quoteMint),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializePlatformConfigInstructionDataEncoder().encode(
      args as InitializePlatformConfigInstructionDataArgs
    ),
    programAddress,
  } as InitializePlatformConfigInstruction<
    TProgramAddress,
    TAccountCreator,
    TAccountPlatformConfig,
    TAccountQuoteMint,
    TAccountSystemProgram
  >);
}

export type ParsedInitializePlatformConfigInstruction<
  TProgram extends string = typeof CBMM_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    creator: TAccountMetas[0];
    platformConfig: TAccountMetas[1];
    quoteMint: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: InitializePlatformConfigInstructionData;
};

export function parseInitializePlatformConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializePlatformConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      creator: getNextAccount(),
      platformConfig: getNextAccount(),
      quoteMint: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializePlatformConfigInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
