/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from '@solana/kit';
import { CPMM_POC_PROGRAM_ADDRESS } from '../programs';
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from '../shared';

export const INITIALIZE_TREASURY_DISCRIMINATOR = new Uint8Array([
  124, 186, 211, 195, 85, 165, 129, 166,
]);

export function getInitializeTreasuryDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INITIALIZE_TREASURY_DISCRIMINATOR
  );
}

export type InitializeTreasuryInstruction<
  TProgram extends string = typeof CPMM_POC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountCentralState extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountTreasuryAta extends string | AccountMeta<string> = string,
  TAccountAMint extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL',
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = '11111111111111111111111111111111',
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountCentralState extends string
        ? WritableAccount<TAccountCentralState>
        : TAccountCentralState,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountTreasuryAta extends string
        ? WritableAccount<TAccountTreasuryAta>
        : TAccountTreasuryAta,
      TAccountAMint extends string
        ? ReadonlyAccount<TAccountAMint>
        : TAccountAMint,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitializeTreasuryInstructionData = {
  discriminator: ReadonlyUint8Array;
  treasuryAuthority: Address;
};

export type InitializeTreasuryInstructionDataArgs = {
  treasuryAuthority: Address;
};

export function getInitializeTreasuryInstructionDataEncoder(): FixedSizeEncoder<InitializeTreasuryInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', fixEncoderSize(getBytesEncoder(), 8)],
      ['treasuryAuthority', getAddressEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INITIALIZE_TREASURY_DISCRIMINATOR })
  );
}

export function getInitializeTreasuryInstructionDataDecoder(): FixedSizeDecoder<InitializeTreasuryInstructionData> {
  return getStructDecoder([
    ['discriminator', fixDecoderSize(getBytesDecoder(), 8)],
    ['treasuryAuthority', getAddressDecoder()],
  ]);
}

export function getInitializeTreasuryInstructionDataCodec(): FixedSizeCodec<
  InitializeTreasuryInstructionDataArgs,
  InitializeTreasuryInstructionData
> {
  return combineCodec(
    getInitializeTreasuryInstructionDataEncoder(),
    getInitializeTreasuryInstructionDataDecoder()
  );
}

export type InitializeTreasuryAsyncInput<
  TAccountAdmin extends string = string,
  TAccountCentralState extends string = string,
  TAccountTreasury extends string = string,
  TAccountTreasuryAta extends string = string,
  TAccountAMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  centralState?: Address<TAccountCentralState>;
  treasury?: Address<TAccountTreasury>;
  treasuryAta?: Address<TAccountTreasuryAta>;
  aMint: Address<TAccountAMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  treasuryAuthority: InitializeTreasuryInstructionDataArgs['treasuryAuthority'];
};

export async function getInitializeTreasuryInstructionAsync<
  TAccountAdmin extends string,
  TAccountCentralState extends string,
  TAccountTreasury extends string,
  TAccountTreasuryAta extends string,
  TAccountAMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CPMM_POC_PROGRAM_ADDRESS,
>(
  input: InitializeTreasuryAsyncInput<
    TAccountAdmin,
    TAccountCentralState,
    TAccountTreasury,
    TAccountTreasuryAta,
    TAccountAMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitializeTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountCentralState,
    TAccountTreasury,
    TAccountTreasuryAta,
    TAccountAMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CPMM_POC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    centralState: { value: input.centralState ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    treasuryAta: { value: input.treasuryAta ?? null, isWritable: true },
    aMint: { value: input.aMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.centralState.value) {
    accounts.centralState.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            99, 101, 110, 116, 114, 97, 108, 95, 115, 116, 97, 116, 101,
          ])
        ),
      ],
    });
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([116, 114, 101, 97, 115, 117, 114, 121])
        ),
        getAddressEncoder().encode(expectAddress(accounts.aMint.value)),
      ],
    });
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.treasuryAta.value) {
    accounts.treasuryAta.value = await getProgramDerivedAddress({
      programAddress:
        'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>,
      seeds: [
        getAddressEncoder().encode(expectAddress(accounts.treasury.value)),
        getAddressEncoder().encode(expectAddress(accounts.tokenProgram.value)),
        getAddressEncoder().encode(expectAddress(accounts.aMint.value)),
      ],
    });
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.centralState),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.treasuryAta),
      getAccountMeta(accounts.aMint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeTreasuryInstructionDataEncoder().encode(
      args as InitializeTreasuryInstructionDataArgs
    ),
    programAddress,
  } as InitializeTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountCentralState,
    TAccountTreasury,
    TAccountTreasuryAta,
    TAccountAMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type InitializeTreasuryInput<
  TAccountAdmin extends string = string,
  TAccountCentralState extends string = string,
  TAccountTreasury extends string = string,
  TAccountTreasuryAta extends string = string,
  TAccountAMint extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  centralState: Address<TAccountCentralState>;
  treasury: Address<TAccountTreasury>;
  treasuryAta: Address<TAccountTreasuryAta>;
  aMint: Address<TAccountAMint>;
  tokenProgram?: Address<TAccountTokenProgram>;
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  treasuryAuthority: InitializeTreasuryInstructionDataArgs['treasuryAuthority'];
};

export function getInitializeTreasuryInstruction<
  TAccountAdmin extends string,
  TAccountCentralState extends string,
  TAccountTreasury extends string,
  TAccountTreasuryAta extends string,
  TAccountAMint extends string,
  TAccountTokenProgram extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CPMM_POC_PROGRAM_ADDRESS,
>(
  input: InitializeTreasuryInput<
    TAccountAdmin,
    TAccountCentralState,
    TAccountTreasury,
    TAccountTreasuryAta,
    TAccountAMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitializeTreasuryInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountCentralState,
  TAccountTreasury,
  TAccountTreasuryAta,
  TAccountAMint,
  TAccountTokenProgram,
  TAccountAssociatedTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CPMM_POC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    centralState: { value: input.centralState ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    treasuryAta: { value: input.treasuryAta ?? null, isWritable: true },
    aMint: { value: input.aMint ?? null, isWritable: false },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA' as Address<'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA'>;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL' as Address<'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'>;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      '11111111111111111111111111111111' as Address<'11111111111111111111111111111111'>;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.admin),
      getAccountMeta(accounts.centralState),
      getAccountMeta(accounts.treasury),
      getAccountMeta(accounts.treasuryAta),
      getAccountMeta(accounts.aMint),
      getAccountMeta(accounts.tokenProgram),
      getAccountMeta(accounts.associatedTokenProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getInitializeTreasuryInstructionDataEncoder().encode(
      args as InitializeTreasuryInstructionDataArgs
    ),
    programAddress,
  } as InitializeTreasuryInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountCentralState,
    TAccountTreasury,
    TAccountTreasuryAta,
    TAccountAMint,
    TAccountTokenProgram,
    TAccountAssociatedTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedInitializeTreasuryInstruction<
  TProgram extends string = typeof CPMM_POC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    centralState: TAccountMetas[1];
    treasury: TAccountMetas[2];
    treasuryAta: TAccountMetas[3];
    aMint: TAccountMetas[4];
    tokenProgram: TAccountMetas[5];
    associatedTokenProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: InitializeTreasuryInstructionData;
};

export function parseInitializeTreasuryInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitializeTreasuryInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      centralState: getNextAccount(),
      treasury: getNextAccount(),
      treasuryAta: getNextAccount(),
      aMint: getNextAccount(),
      tokenProgram: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitializeTreasuryInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
