/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type BurnEvent = {
  burnAmount: bigint;
  topupAccrued: bigint;
  newBReserve: bigint;
  newAReserve: bigint;
  newOutstandingTopup: bigint;
  newVirtualReserve: bigint;
  newBuybackFeesBalance: bigint;
};

export type BurnEventArgs = {
  burnAmount: number | bigint;
  topupAccrued: number | bigint;
  newBReserve: number | bigint;
  newAReserve: number | bigint;
  newOutstandingTopup: number | bigint;
  newVirtualReserve: number | bigint;
  newBuybackFeesBalance: number | bigint;
};

export function getBurnEventEncoder(): FixedSizeEncoder<BurnEventArgs> {
  return getStructEncoder([
    ['burnAmount', getU64Encoder()],
    ['topupAccrued', getU64Encoder()],
    ['newBReserve', getU64Encoder()],
    ['newAReserve', getU64Encoder()],
    ['newOutstandingTopup', getU64Encoder()],
    ['newVirtualReserve', getU64Encoder()],
    ['newBuybackFeesBalance', getU64Encoder()],
  ]);
}

export function getBurnEventDecoder(): FixedSizeDecoder<BurnEvent> {
  return getStructDecoder([
    ['burnAmount', getU64Decoder()],
    ['topupAccrued', getU64Decoder()],
    ['newBReserve', getU64Decoder()],
    ['newAReserve', getU64Decoder()],
    ['newOutstandingTopup', getU64Decoder()],
    ['newVirtualReserve', getU64Decoder()],
    ['newBuybackFeesBalance', getU64Decoder()],
  ]);
}

export function getBurnEventCodec(): FixedSizeCodec<BurnEventArgs, BurnEvent> {
  return combineCodec(getBurnEventEncoder(), getBurnEventDecoder());
}
