/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU16Decoder,
  getU16Encoder,
  getU32Decoder,
  getU32Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';
import {
  getBurnRoleDecoder,
  getBurnRoleEncoder,
  type BurnRole,
  type BurnRoleArgs,
} from '.';

export type BurnTier = {
  burnBpX100: number;
  role: BurnRole;
  maxDailyBurns: number;
};

export type BurnTierArgs = {
  burnBpX100: number;
  role: BurnRoleArgs;
  maxDailyBurns: number;
};

export function getBurnTierEncoder(): Encoder<BurnTierArgs> {
  return getStructEncoder([
    ['burnBpX100', getU32Encoder()],
    ['role', getBurnRoleEncoder()],
    ['maxDailyBurns', getU16Encoder()],
  ]);
}

export function getBurnTierDecoder(): Decoder<BurnTier> {
  return getStructDecoder([
    ['burnBpX100', getU32Decoder()],
    ['role', getBurnRoleDecoder()],
    ['maxDailyBurns', getU16Decoder()],
  ]);
}

export function getBurnTierCodec(): Codec<BurnTierArgs, BurnTier> {
  return combineCodec(getBurnTierEncoder(), getBurnTierDecoder());
}
