/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

export type BuyEvent = {
  quoteInput: bigint;
  baseOutput: bigint;
  fees: bigint;
  topupPaid: bigint;
  newBaseReserve: bigint;
  newQuoteReserve: bigint;
  buyer: Address;
  pool: Address;
};

export type BuyEventArgs = {
  quoteInput: number | bigint;
  baseOutput: number | bigint;
  fees: number | bigint;
  topupPaid: number | bigint;
  newBaseReserve: number | bigint;
  newQuoteReserve: number | bigint;
  buyer: Address;
  pool: Address;
};

export function getBuyEventEncoder(): FixedSizeEncoder<BuyEventArgs> {
  return getStructEncoder([
    ['quoteInput', getU64Encoder()],
    ['baseOutput', getU64Encoder()],
    ['fees', getU64Encoder()],
    ['topupPaid', getU64Encoder()],
    ['newBaseReserve', getU64Encoder()],
    ['newQuoteReserve', getU64Encoder()],
    ['buyer', getAddressEncoder()],
    ['pool', getAddressEncoder()],
  ]);
}

export function getBuyEventDecoder(): FixedSizeDecoder<BuyEvent> {
  return getStructDecoder([
    ['quoteInput', getU64Decoder()],
    ['baseOutput', getU64Decoder()],
    ['fees', getU64Decoder()],
    ['topupPaid', getU64Decoder()],
    ['newBaseReserve', getU64Decoder()],
    ['newQuoteReserve', getU64Decoder()],
    ['buyer', getAddressDecoder()],
    ['pool', getAddressDecoder()],
  ]);
}

export function getBuyEventCodec(): FixedSizeCodec<BuyEventArgs, BuyEvent> {
  return combineCodec(getBuyEventEncoder(), getBuyEventDecoder());
}
