//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_pubkey::{pubkey, Pubkey};


  /// `cbmm` program ID.
  pub const CBMM_ID: Pubkey = pubkey!("CBMMzs3HKfTMudbXifeNcw3NcHQhZX7izDBKoGDLRdjj");

